
[project]
name = "qyro-cli"
version = "1.0.0a2"
description = "The official developer CLI and project orchestrator for the Qyro ecosystem. Scaffold, develop, build, package, and sign cross-platform Python applications."
authors = [{ name = "Neuri", email = "ppg@neuri.ai" }]
maintainers = [
    { name = "Luis Alfredo De Los Reyes", email = "luisalfredoreyes98@gmail.com" },
]
dynamic = ["classifiers"]
keywords = [
    "ppg", "python", "cli", "python-cli", "developer-tools", "build-tool",
    "project-generator", "app-packaging", "packaging", "code-signing", "cross-platform",
    "desktop-app", "mobile-app", "pyinstaller", "pyqt", "pyside", "pyside6", 
    "kivy", "tkinter"
]

license = "MIT"
requires-python = ">=3.10,<3.16"
readme = "README.md"

dependencies = [
    "requests>=2.34.2,<3.0.0",
    "semver>=3.1.0,<4.0.0",
    "rich>=15.0.0,<16.0.0",
    "prompt-toolkit>=3.0.53,<4.0.0",
    "questionary>=2.1.1,<3.0.0",
    "qyro-engine>=1.0.0a1,<2.0.0",
    "cryptography>=45.0.0,<47.0.0"
]

[project.optional-dependencies]
desktop = [
    "pyinstaller>=6.22.3,<7.0.0",
    "pillow>=11.0.0,<13.0.0",
    "cython>=3.0.12,<4.0.0",
]

mobile = [
    "buildozer>=1.5.0",
]

[project.scripts]
qyro = "qyro_cli.cmdline.app:main"

[tool.poetry]
package-mode = true

packages = [{ include = "qyro_cli" }]

classifiers = [
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Topic :: Software Development :: Libraries",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Programming Language :: Python :: 3.15",
]

[tool.poetry.group.dev.dependencies]
pytest = ">=9.0.0"
pytest-cov = ">=4.1.0"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
